name: 'Setup Rust'
description: 'Setup Rust toolchain with Namespace cache'

inputs:
  toolchain:
    description: 'Rust toolchain version'
    default: 'stable'
  components:
    description: 'Rust components (comma-separated)'
    default: 'rustfmt, clippy'
  targets:
    description: 'Additional targets (comma-separated)'
    default: ''

runs:
  using: 'composite'
  steps:
    # Namespace runners come with rustup bootstrapped (but no toolchain installed).
    # Remove it so the cache action can mount our cached ~/.rustup without warnings.
    - name: Remove pre-existing rustup
      shell: bash
      run: rm -rf ~/.rustup

    - name: Set up Rust cache
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        cache: rust
        path: ~/.rustup

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}
