name: 'Setup Rust'
description: 'Setup Rust toolchain with Namespace cache'

inputs:
  toolchain:
    description: 'Rust toolchain version'
    default: 'stable'
  components:
    description: 'Additional components (comma-separated)'
    default: ''
  targets:
    description: 'Additional targets (comma-separated)'
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Rust cache
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        cache: rust

    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}
        targets: ${{ inputs.targets }}
